name: your_schedule
description: Filter your Untis Schedule by classes you have chosen.

version: 0.0.1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  logger: ^1.1.0
  flutter_riverpod: ^2.0.0-dev.9
  flutter_secure_storage: ^6.0.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true