name: your_schedule
description: Filter your Untis Schedule by classes you have chosen.

version: 1.3.12

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  logger: ^2.0.2+1
  flutter_material_color_picker: ^1.2.0
  flutter_riverpod: ^2.4.4
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  intl: ^0.18.1
  linked_scroll_controller: ^0.2.0
  flutter_native_splash: ^2.3.4
  sentry_flutter: ^7.10.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  otp: ^3.1.4
  riverpod_annotation: ^2.2.1
  dart_extensions_methods: ^2.0.0
  connectivity_plus: ^5.0.1
  animations: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.5

flutter_icons:
  android: true
  ios: true
  image_path: "assets/school_padding.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/school_padding.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/school_padding.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/school_padding.png
    - assets/school_blue.png