name: your_schedule
description: Filter your Untis Schedule by classes you have chosen.

version: 1.2.7

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  logger: ^1.1.0
  flutter_material_color_picker: ^1.1.0+2
  flutter_riverpod: ^2.0.0-dev.9
  flutter_secure_storage: ^5.1.2
  shared_preferences: ^2.0.15
  google_fonts: ^3.0.1
  intl: ^0.17.0
  linked_scroll_controller: ^0.2.0
  flutter_native_splash: ^2.2.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/school_padding.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/school_padding.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/school_padding.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/school_padding.png
    - assets/school_blue.png