name: your_schedule
description: Filter your Untis Schedule by classes you have chosen.

version: 1.4.7+1407

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  logger: ^2.6.1
  flutter_material_color_picker: ^1.2.0
  flutter_riverpod: ^3.0.0-dev.17
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  google_fonts: ^6.3.0
  intl: ^0.20.2
  flutter_native_splash: ^2.4.6
  sentry_flutter: ^9.7.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  otp: ^3.2.0
  riverpod_annotation: ^3.0.0-dev.17
  dart_extensions_methods: ^2.0.0
  connectivity_plus: ^6.1.5
  animations: ^2.0.11
  flutter_local_notifications: ^19.4.0
  workmanager: ^0.9.0+2
  permission_handler: ^12.0.1
  mobile_scanner: ^7.1.3
  vibration: ^3.1.4

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.7.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  riverpod_generator: ^3.0.0-dev.17
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0-dev.17
  #freezed_lint: ^0.0.10

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/school_padding.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/school_padding.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/school_padding.png"
  android: true
  ios: false

flutter:
  uses-material-design: true
  assets:
    - assets/school_padding.png
    - assets/school_blue.png