name: your_schedule
description: Filter your Untis Schedule by classes you have chosen.

version: 1.4.2+1402

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  logger: ^2.3.0
  flutter_material_color_picker: ^1.2.0
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  intl: ^0.19.0
  flutter_native_splash: ^2.4.0
  sentry_flutter: ^8.2.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  otp: ^3.1.4
  riverpod_annotation: ^2.3.5
  dart_extensions_methods: ^2.0.0
  connectivity_plus: ^6.0.3
  animations: ^2.0.11
  flutter_local_notifications: ^17.1.2
  workmanager: ^0.5.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  freezed_lint: ^0.0.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/school_padding.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/school_padding.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/school_padding.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/school_padding.png
    - assets/school_blue.png